version: "3.8"

volumes:
  mongoid: {}

services:
  mongoid:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongoid:/var/lib/mongoid
    ports: [ "127.0.0.1:27017:27017" ]

