name: release
on:
  workflow_dispatch:

jobs:
  release:
    name: Release to rubygems
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true
      - name: Run Build
        run: bundle exec rake build
      - name: Configure Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
#      - name: Save credentials
#        run: |
#          mkdir -p $HOME/.gem
#          mkdir -p $HOME/.local/share/gem
#          touch $HOME/.gem/credentials
#          touch $HOME/.local/share/gem/credentials
#          chmod 0600 $HOME/.gem/credentials
#          chmod 0600 $HOME/.local/share/gem/credentials
#          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}\n" > $HOME/.gem/credentials
#          printf -- "---\n:rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}\n" > $HOME/.local/share/gem/credentials
      - name: Publish to Rubygems
        run: RUBYGEMS_API_KEY="${{secrets.RUBYGEMS_API_KEY}}" bundle exec rake release